export const SYSTEM_SETTINGS_TABS = [
  { value: 'system-settings-general', icon: 'tabler-settings', title: 'Cấu hình chung' },
  { value: 'system-settings-admin-experience', icon: 'tabler-device-desktop', title: 'Giao diện quản trị' },
  { value: 'system-settings-public-channels', icon: 'tabler-share', title: 'Kênh công khai' },
  { value: 'system-settings-integrations', icon: 'tabler-api', title: 'Tích hợp hệ thống' },
  { value: 'system-settings-notifications', icon: 'tabler-mail', title: 'Thông báo' },
]

export const systemSettingsPageMeta = {
  general: {
    title: 'Cấu hình chung',
    subtitle: 'Quản lý cấu hình nền tảng, ngôn ngữ, logo, favicon và thời gian lưu nhật ký.',
    icon: 'tabler-settings',
    color: 'info',
    saveLabel: 'Lưu cấu hình',
    loadErrorMessage: 'Không thể tải cấu hình chung.',
    saveSuccessMessage: 'Lưu cấu hình chung thành công.',
    saveErrorMessage: 'Không thể lưu cấu hình chung.',
    sections: [
      {
        fields: [
          { key: 'copyright', group: 'general', label: 'Thông tin bản quyền', type: 'text', cols: 12, md: 6 },
          { key: 'designed_by', group: 'general', label: 'Thiết kế bởi', type: 'text', cols: 12, md: 6 },
          {
            key: 'language',
            group: 'general',
            label: 'Ngôn ngữ',
            type: 'select',
            cols: 12,
            md: 6,
            defaultValue: 'vi',
            items: [
              { title: 'Tiếng Việt', value: 'vi' },
              { title: 'English', value: 'en' },
            ],
            transform: 'string',
          },
          {
            key: 'time_format',
            group: 'general',
            label: 'Định dạng thời gian',
            type: 'select',
            cols: 12,
            md: 6,
            defaultValue: 'H:i:s d/m/Y',
            items: [
              { title: '24h đầy đủ', value: 'H:i:s d/m/Y' },
              { title: '24h ngắn', value: 'Y-m-d H:i' },
              { title: '12h đầy đủ', value: 'h:i A d/m/Y' },
            ],
            transform: 'string',
          },
          {
            key: 'log_retention_days',
            group: 'log',
            label: 'Số ngày lưu nhật ký',
            type: 'number',
            cols: 12,
            md: 6,
            defaultValue: 90,
            transform: 'number',
          },
        ],
      },
    ],
  },
  adminExperience: {
    title: 'Giao diện quản trị',
    subtitle: 'Cấu hình nội dung hiển thị cho trang quản trị và trang chọn tổ chức.',
    icon: 'tabler-device-desktop',
    color: 'info',
    saveLabel: 'Lưu cấu hình',
    loadErrorMessage: 'Không thể tải cấu hình giao diện quản trị.',
    saveSuccessMessage: 'Lưu cấu hình trải nghiệm quản trị thành công.',
    saveErrorMessage: 'Không thể lưu cấu hình trải nghiệm quản trị.',
    sections: [
      {
        title: 'Trang quản trị',
        fields: [
          { key: 'admin_app_name', group: 'admin_page', label: 'Tên ứng dụng', type: 'text', cols: 12, md: 6 },
          { key: 'admin_logo_title', group: 'admin_page', label: 'Tiêu đề logo', type: 'text', cols: 12, md: 6 },
          { key: 'admin_welcome_title', group: 'admin_page', label: 'Tiêu đề chào mừng', type: 'text', cols: 12, md: 6 },
          { key: 'admin_background_image', group: 'admin_page', label: 'Ảnh nền trang quản trị', type: 'text', cols: 12, md: 6 },
          { key: 'admin_app_description', group: 'admin_page', label: 'Mô tả ứng dụng', type: 'textarea', cols: 12, rows: 3 },
        ],
      },
      {
        title: 'Trang chọn tổ chức',
        fields: [
          { key: 'org_select_title', group: 'org_select_page', label: 'Tiêu đề trang chọn tổ chức', type: 'text', cols: 12, md: 6 },
          { key: 'org_select_background_image', group: 'org_select_page', label: 'Ảnh nền trang chọn tổ chức', type: 'text', cols: 12, md: 6 },
          { key: 'org_select_description', group: 'org_select_page', label: 'Mô tả trang chọn tổ chức', type: 'textarea', cols: 12, rows: 3 },
        ],
      },
    ],
  },
  publicChannels: {
    title: 'Kênh công khai',
    subtitle: 'Quản lý các đường dẫn mạng xã hội và thông tin liên hệ công khai.',
    icon: 'tabler-share',
    color: 'primary',
    saveLabel: 'Lưu cấu hình',
    loadErrorMessage: 'Không thể tải cấu hình kênh công khai.',
    saveSuccessMessage: 'Lưu cấu hình kênh công khai thành công.',
    saveErrorMessage: 'Không thể lưu cấu hình kênh công khai.',
    sections: [
      {
        fields: [
          { key: 'social_facebook', group: 'social', label: 'Facebook', type: 'text', cols: 12, md: 6 },
          { key: 'social_twitter', group: 'social', label: 'Twitter', type: 'text', cols: 12, md: 6 },
          { key: 'social_youtube', group: 'social', label: 'YouTube', type: 'text', cols: 12, md: 6 },
          { key: 'social_tiktok', group: 'social', label: 'TikTok', type: 'text', cols: 12, md: 6 },
          { key: 'social_gmail', group: 'social', label: 'Gmail', type: 'text', cols: 12, md: 6 },
          { key: 'social_email', group: 'social', label: 'Email', type: 'text', cols: 12, md: 6 },
        ],
      },
    ],
  },
  integrations: {
    title: 'Tích hợp hệ thống',
    subtitle: 'Quản lý các khóa kết nối API, SMS, Zalo và Chat đang có ở backend.',
    icon: 'tabler-api',
    color: 'warning',
    saveLabel: 'Lưu cấu hình',
    loadErrorMessage: 'Không thể tải cấu hình tích hợp.',
    saveSuccessMessage: 'Lưu cấu hình tích hợp thành công.',
    saveErrorMessage: 'Không thể lưu cấu hình tích hợp.',
    sections: [
      {
        title: 'API services',
        fields: [
          { key: 'api_gemini_url', group: 'api', label: 'Gemini API URL', type: 'text', cols: 12, md: 6 },
          { key: 'api_gemini_token', group: 'api', label: 'Gemini Token', type: 'password', cols: 12, md: 6 },
          { key: 'api_deepseek_url', group: 'api', label: 'DeepSeek API URL', type: 'text', cols: 12, md: 6 },
          { key: 'api_deepseek_token', group: 'api', label: 'DeepSeek Token', type: 'password', cols: 12, md: 6 },
          { key: 'api_chatgpt_url', group: 'api', label: 'ChatGPT API URL', type: 'text', cols: 12, md: 6 },
          { key: 'api_chatgpt_token', group: 'api', label: 'ChatGPT Token', type: 'password', cols: 12, md: 6 },
          { key: 'api_firebase_url', group: 'api', label: 'Firebase API URL', type: 'text', cols: 12, md: 6 },
          { key: 'api_firebase_token', group: 'api', label: 'Firebase Token', type: 'password', cols: 12, md: 6 },
          { key: 'api_google_maps_url', group: 'api', label: 'Google Maps API URL', type: 'text', cols: 12, md: 6 },
          { key: 'api_google_maps_token', group: 'api', label: 'Google Maps Token', type: 'password', cols: 12, md: 6 },
          { key: 'api_firebase_enabled', group: 'api', label: 'Bật Firebase', type: 'switch', cols: 12, defaultValue: false, transform: 'boolean' },
        ],
      },
      {
        title: 'SMS',
        fields: [
          { key: 'sms_server', group: 'sms', label: 'Máy chủ SMS', type: 'text', cols: 12, md: 6 },
          { key: 'sms_username', group: 'sms', label: 'Tên đăng nhập SMS', type: 'text', cols: 12, md: 6 },
          { key: 'sms_password', group: 'sms', label: 'Mật khẩu SMS', type: 'password', cols: 12, md: 6 },
          { key: 'sms_test_phone', group: 'sms', label: 'Số điện thoại kiểm thử', type: 'text', cols: 12, md: 6 },
        ],
      },
      {
        title: 'Zalo',
        fields: [
          { key: 'zalo_server', group: 'zalo', label: 'Máy chủ Zalo', type: 'text', cols: 12, md: 6 },
          { key: 'zalo_username', group: 'zalo', label: 'Tên đăng nhập Zalo', type: 'text', cols: 12, md: 6 },
          { key: 'zalo_password', group: 'zalo', label: 'Mật khẩu Zalo', type: 'password', cols: 12, md: 6 },
          { key: 'zalo_sender', group: 'zalo', label: 'Người gửi Zalo', type: 'text', cols: 12, md: 6 },
          { key: 'zalo_template_id', group: 'zalo', label: 'Template ID', type: 'text', cols: 12, md: 6 },
          {
            key: 'zalo_extra_params',
            group: 'zalo',
            label: 'Zalo extra params (JSON)',
            type: 'textarea',
            cols: 12,
            rows: 4,
            transform: 'json',
            placeholder: '{\n  "key": "value"\n}',
          },
        ],
      },
      {
        title: 'Chat',
        fields: [
          { key: 'chat_server', group: 'chat', label: 'Máy chủ Chat', type: 'text', cols: 12, md: 6 },
          { key: 'chat_api_key', group: 'chat', label: 'Chat API Key', type: 'password', cols: 12, md: 6 },
          { key: 'chat_sender', group: 'chat', label: 'Người gửi', type: 'text', cols: 12, md: 6 },
          { key: 'chat_receiver', group: 'chat', label: 'Người nhận', type: 'text', cols: 12, md: 6 },
          { key: 'chat_room', group: 'chat', label: 'Phòng chat', type: 'text', cols: 12, md: 6 },
          { key: 'chat_department', group: 'chat', label: 'Phòng ban', type: 'text', cols: 12, md: 6 },
          { key: 'chat_email_title', group: 'chat', label: 'Tiêu đề email', type: 'text', cols: 12, md: 6 },
          { key: 'chat_test_type', group: 'chat', label: 'Loại kiểm tra', type: 'text', cols: 12, md: 6 },
          { key: 'chat_message', group: 'chat', label: 'Tin nhắn mặc định', type: 'textarea', cols: 12, rows: 3 },
        ],
      },
    ],
  },
  notifications: {
    title: 'Cấu hình thông báo',
    subtitle: 'Quản lý cấu hình email và SMTP dùng cho gửi thông báo hệ thống.',
    icon: 'tabler-mail',
    color: 'primary',
    saveLabel: 'Lưu cấu hình',
    loadErrorMessage: 'Không thể tải cấu hình thông báo.',
    saveSuccessMessage: 'Lưu cấu hình thông báo thành công.',
    saveErrorMessage: 'Không thể lưu cấu hình thông báo.',
    notice: 'Các thay đổi sẽ áp dụng cho cơ chế gửi email của hệ thống.',
    sections: [
      {
        fields: [
          {
            key: 'email_protocol',
            group: 'email',
            label: 'Giao thức',
            type: 'select',
            cols: 12,
            md: 6,
            defaultValue: 'smtp',
            transform: 'string',
            items: [{ title: 'SMTP', value: 'smtp' }],
          },
          { key: 'email_sender_name', group: 'email', label: 'Tên người gửi', type: 'text', cols: 12, md: 6 },
          { key: 'email_sender_address', group: 'email', label: 'Địa chỉ email gửi', type: 'text', cols: 12, md: 6 },
          { key: 'email_smtp_host', group: 'email', label: 'Máy chủ SMTP', type: 'text', cols: 12, md: 6 },
          { key: 'email_smtp_port', group: 'email', label: 'Cổng SMTP', type: 'number', cols: 12, md: 6, defaultValue: '587', transform: 'string' },
          { key: 'email_smtp_username', group: 'email', label: 'Tài khoản SMTP', type: 'text', cols: 12, md: 6 },
          { key: 'email_smtp_password', group: 'email', label: 'Mật khẩu SMTP', type: 'password', cols: 12, md: 6 },
          {
            key: 'email_smtp_encryption',
            group: 'email',
            label: 'Loại bảo mật',
            type: 'select',
            cols: 12,
            md: 6,
            defaultValue: 'tls',
            transform: 'string',
            items: [
              { title: 'TLS', value: 'tls' },
              { title: 'SSL', value: 'ssl' },
              { title: 'Không dùng', value: 'none' },
            ],
          },
          { key: 'email_test_address', group: 'email', label: 'Email kiểm thử', type: 'text', cols: 12, md: 6 },
        ],
      },
    ],
  },
}
