export default {
  name: 'permissions',
  displayName: 'Permissions',
  group: 'auth',
  navOrder: 110,
  path: 'src/modules/auth/permissions',
  servicePaths: ['src/modules/auth/permissions/services/permissionService.js'],
  purpose: 'Quan ly danh sach permission va nhom quyen hien thi tren frontend.',
  features: [
    'Danh sach permission',
    'Tao, sua, xoa permission',
    'Tree permission',
    'Thong ke',
    'Import/export Excel',
    'Tu quan ly navigation item cua module permissions',
  ],
  api: [
    { method: 'GET', endpoint: '/permissions', service: 'fetchPermissions', description: 'Danh sach permission' },
    { method: 'GET', endpoint: '/permissions/:id', service: 'fetchPermission', description: 'Chi tiet permission' },
    { method: 'POST', endpoint: '/permissions', service: 'createPermission', description: 'Tao permission' },
    { method: 'PUT', endpoint: '/permissions/:id', service: 'updatePermission', description: 'Cap nhat permission' },
    { method: 'DELETE', endpoint: '/permissions/:id', service: 'deletePermission', description: 'Xoa permission' },
    { method: 'GET', endpoint: '/permissions/tree', service: 'fetchPermissionTree', description: 'Cay permission' },
    { method: 'POST', endpoint: '/permissions/bulk-delete', service: 'bulkDeletePermissions', description: 'Xoa hang loat' },
    { method: 'GET', endpoint: '/permissions/stats', service: 'fetchPermissionStats', description: 'Thong ke permission' },
    { method: 'GET', endpoint: '/permissions/export', service: 'exportPermissions', description: 'Xuat Excel' },
    { method: 'GET', endpoint: '/permissions/template', service: 'downloadPermissionTemplate', description: 'Tai file mau' },
    { method: 'POST', endpoint: '/permissions/import', service: 'importPermissions', description: 'Nhap Excel' },
  ],
}
