export const coreSettingGroups = [
  {
    key: 'general',
    titleKey: 'settings.general',
    icon: 'tabler-settings-cog',
    subtitleKey: 'settings.general.subtitle',
    fields: [
      { key: 'copyright', labelKey: 'settings.general.copyright', type: 'text', cols: 6 },
      { key: 'designed_by', labelKey: 'settings.general.designed_by', type: 'text', cols: 6 },
      {
        key: 'language',
        labelKey: 'settings.general.language',
        type: 'select',
        cols: 6,
        items: [
          { title: 'Tiếng Việt', value: 'vi' },
          { title: 'English', value: 'en' },
        ],
      },
      {
        key: 'time_format',
        labelKey: 'settings.general.time_format',
        type: 'select',
        cols: 6,
        items: [
          { title: '24h', value: '24h' },
          { title: '12h', value: '12h' },
        ],
      },
      {
        key: 'icon',
        labelKey: 'settings.general.icon',
        type: 'image',
        accept: '.ico,.gif,.png,.jpg,.jpeg,.svg',
        hintKey: 'settings.general.icon',
      },
      {
        key: 'logo',
        labelKey: 'settings.general.logo',
        type: 'image',
        accept: '.svg,.png,.jpg,.jpeg',
        hintKey: 'settings.general.logo',
      },
    ],
  },
  {
    key: 'admin_page',
    titleKey: 'settings.admin_page',
    icon: 'tabler-layout-dashboard',
    subtitleKey: 'settings.admin_page.subtitle',
    fields: [
      { key: 'admin_app_name', labelKey: 'settings.admin_page.admin_app_name', type: 'text', cols: 6 },
      { key: 'admin_logo_title', labelKey: 'settings.admin_page.admin_logo_title', type: 'text', cols: 6 },
      { key: 'admin_welcome_title', labelKey: 'settings.admin_page.admin_welcome_title', type: 'text', cols: 12 },
      { key: 'admin_app_description', labelKey: 'settings.admin_page.admin_app_description', type: 'textarea', cols: 12, rows: 4 },
      {
        key: 'admin_background_image',
        labelKey: 'settings.admin_page.admin_background_image',
        type: 'image',
        accept: '.png,.jpg,.jpeg,.webp,.svg',
        hintKey: 'settings.admin_page.admin_background_image',
      },
    ],
  },
  {
    key: 'org_select_page',
    titleKey: 'settings.org_select_page',
    icon: 'tabler-building-community',
    subtitleKey: 'settings.org_select_page.subtitle',
    fields: [
      { key: 'org_select_title', labelKey: 'settings.org_select_page.org_select_title', type: 'text', cols: 12 },
      { key: 'org_select_description', labelKey: 'settings.org_select_page.org_select_description', type: 'textarea', cols: 12, rows: 4 },
      {
        key: 'org_select_background_image',
        labelKey: 'settings.org_select_page.org_select_background_image',
        type: 'image',
        accept: '.png,.jpg,.jpeg,.webp,.svg',
        hintKey: 'settings.org_select_page.org_select_background_image',
      },
    ],
  },
  {
    key: 'social',
    titleKey: 'settings.social',
    icon: 'tabler-brand-facebook',
    subtitleKey: 'settings.social.subtitle',
    fields: [
      { key: 'social_facebook', labelKey: 'settings.social.social_facebook', type: 'text', cols: 6 },
      { key: 'social_twitter', labelKey: 'settings.social.social_twitter', type: 'text', cols: 6 },
      { key: 'social_youtube', labelKey: 'settings.social.social_youtube', type: 'text', cols: 6 },
      { key: 'social_tiktok', labelKey: 'settings.social.social_tiktok', type: 'text', cols: 6 },
      { key: 'social_gmail', labelKey: 'settings.social.social_gmail', type: 'text', cols: 6 },
      { key: 'social_email', labelKey: 'settings.social.social_email', type: 'text', cols: 6 },
    ],
  },
  {
    key: 'api',
    titleKey: 'settings.api',
    icon: 'tabler-plug-connected',
    subtitleKey: 'settings.api.subtitle',
    fields: [
      { key: 'api_gemini_url', labelKey: 'settings.api.api_gemini_url', type: 'text', cols: 6 },
      { key: 'api_gemini_token', labelKey: 'settings.api.api_gemini_token', type: 'password', cols: 6 },
      { key: 'api_deepseek_url', labelKey: 'settings.api.api_deepseek_url', type: 'text', cols: 6 },
      { key: 'api_deepseek_token', labelKey: 'settings.api.api_deepseek_token', type: 'password', cols: 6 },
      { key: 'api_chatgpt_url', labelKey: 'settings.api.api_chatgpt_url', type: 'text', cols: 6 },
      { key: 'api_chatgpt_token', labelKey: 'settings.api.api_chatgpt_token', type: 'password', cols: 6 },
      { key: 'api_firebase_url', labelKey: 'settings.api.api_firebase_url', type: 'text', cols: 6 },
      { key: 'api_firebase_token', labelKey: 'settings.api.api_firebase_token', type: 'password', cols: 6 },
      { key: 'api_google_maps_url', labelKey: 'settings.api.api_google_maps_url', type: 'text', cols: 6 },
      { key: 'api_google_maps_token', labelKey: 'settings.api.api_google_maps_token', type: 'password', cols: 6 },
      { key: 'api_firebase_enabled', labelKey: 'settings.api.api_firebase_enabled', type: 'switch', cols: 12 },
    ],
  },
  {
    key: 'email',
    titleKey: 'settings.email',
    icon: 'tabler-mail',
    subtitleKey: 'settings.email.subtitle',
    fields: [
      {
        key: 'email_protocol',
        labelKey: 'settings.email.email_protocol',
        type: 'select',
        cols: 6,
        items: [
          { title: 'SMTP', value: 'smtp' },
          { title: 'Sendmail', value: 'sendmail' },
        ],
      },
      { key: 'email_sender_name', labelKey: 'settings.email.email_sender_name', type: 'text', cols: 6 },
      { key: 'email_sender_address', labelKey: 'settings.email.email_sender_address', type: 'text', cols: 6 },
      { key: 'email_smtp_host', labelKey: 'settings.email.email_smtp_host', type: 'text', cols: 6 },
      { key: 'email_smtp_username', labelKey: 'settings.email.email_smtp_username', type: 'text', cols: 6 },
      { key: 'email_smtp_password', labelKey: 'settings.email.email_smtp_password', type: 'password', cols: 6 },
      { key: 'email_smtp_port', labelKey: 'settings.email.email_smtp_port', type: 'number', cols: 6 },
      {
        key: 'email_smtp_encryption',
        labelKey: 'settings.email.email_smtp_encryption',
        type: 'select',
        cols: 6,
        items: [
          { title: 'TLS', value: 'tls' },
          { title: 'SSL', value: 'ssl' },
          { title: 'None', value: 'none' },
        ],
      },
      { key: 'email_test_address', labelKey: 'settings.email.email_test_address', type: 'text', cols: 6 },
    ],
  },
  {
    key: 'sms',
    titleKey: 'settings.sms',
    icon: 'tabler-message',
    subtitleKey: 'settings.sms.subtitle',
    fields: [
      { key: 'sms_server', labelKey: 'settings.sms.sms_server', type: 'text', cols: 6 },
      { key: 'sms_username', labelKey: 'settings.sms.sms_username', type: 'text', cols: 6 },
      { key: 'sms_password', labelKey: 'settings.sms.sms_password', type: 'password', cols: 6 },
      { key: 'sms_test_phone', labelKey: 'settings.sms.sms_test_phone', type: 'text', cols: 6 },
    ],
  },
  {
    key: 'zalo',
    titleKey: 'settings.zalo',
    icon: 'tabler-brand-telegram',
    subtitleKey: 'settings.zalo.subtitle',
    fields: [
      { key: 'zalo_server', labelKey: 'settings.zalo.zalo_server', type: 'text', cols: 6 },
      { key: 'zalo_username', labelKey: 'settings.zalo.zalo_username', type: 'text', cols: 6 },
      { key: 'zalo_password', labelKey: 'settings.zalo.zalo_password', type: 'password', cols: 6 },
      { key: 'zalo_sender', labelKey: 'settings.zalo.zalo_sender', type: 'text', cols: 6 },
      { key: 'zalo_template_id', labelKey: 'settings.zalo.zalo_template_id', type: 'text', cols: 6 },
      { key: 'zalo_extra_params', labelKey: 'settings.zalo.zalo_extra_params', type: 'textarea', cols: 12, rows: 4 },
    ],
  },
  {
    key: 'chat',
    titleKey: 'settings.chat',
    icon: 'tabler-messages',
    subtitleKey: 'settings.chat.subtitle',
    fields: [
      { key: 'chat_server', labelKey: 'settings.chat.chat_server', type: 'text', cols: 6 },
      { key: 'chat_api_key', labelKey: 'settings.chat.chat_api_key', type: 'password', cols: 6 },
      { key: 'chat_sender', labelKey: 'settings.chat.chat_sender', type: 'text', cols: 6 },
      { key: 'chat_receiver', labelKey: 'settings.chat.chat_receiver', type: 'text', cols: 6 },
      { key: 'chat_room', labelKey: 'settings.chat.chat_room', type: 'text', cols: 6 },
      { key: 'chat_message', labelKey: 'settings.chat.chat_message', type: 'textarea', cols: 6, rows: 4 },
      { key: 'chat_department', labelKey: 'settings.chat.chat_department', type: 'text', cols: 6 },
      { key: 'chat_email_title', labelKey: 'settings.chat.chat_email_title', type: 'text', cols: 6 },
      { key: 'chat_test_type', labelKey: 'settings.chat.chat_test_type', type: 'text', cols: 6 },
    ],
  },
  {
    key: 'log',
    titleKey: 'settings.log',
    icon: 'tabler-file-text',
    subtitleKey: 'settings.log.subtitle',
    fields: [
      { key: 'log_retention_days', labelKey: 'settings.log.log_retention_days', type: 'number', cols: 6 },
    ],
  },
]

export const createEmptySettingState = () => Object.fromEntries(
  coreSettingGroups.map(group => [
    group.key,
    Object.fromEntries(group.fields.map(field => [field.key, field.type === 'switch' ? false : ''])),
  ]),
)
