export const coreSettingGroups = [
  {
    key: 'general',
    title: 'Cấu hình chung',
    icon: 'tabler-settings-cog',
    subtitle: 'Thiết lập ngôn ngữ, thời gian và bộ nhận diện chung của hệ thống.',
    fields: [
      { key: 'copyright', label: 'Bản quyền', type: 'text', cols: 6 },
      { key: 'designed_by', label: 'Thiết kế bởi', type: 'text', cols: 6 },
      {
        key: 'language',
        label: 'Ngôn ngữ',
        type: 'select',
        cols: 6,
        items: [
          { title: 'Tiếng Việt', value: 'vi' },
          { title: 'English', value: 'en' },
        ],
      },
      {
        key: 'time_format',
        label: 'Định dạng thời gian',
        type: 'select',
        cols: 6,
        items: [
          { title: '24h', value: '24h' },
          { title: '12h', value: '12h' },
        ],
      },
      {
        key: 'icon',
        label: 'Biểu tượng trang',
        type: 'image',
        accept: '.ico,.gif,.png,.jpg,.jpeg,.svg',
        hint: 'Cho phép ICO, GIF, PNG, JPG, SVG.',
      },
      {
        key: 'logo',
        label: 'Logo hệ thống',
        type: 'image',
        accept: '.svg,.png,.jpg,.jpeg',
        hint: 'Cho phép SVG, PNG, JPG, JPEG.',
      },
    ],
  },
  {
    key: 'admin_page',
    title: 'Trang quản trị',
    icon: 'tabler-layout-dashboard',
    subtitle: 'Nội dung hiển thị cho trang quản trị và màn chào mừng.',
    fields: [
      { key: 'admin_app_name', label: 'Tên ứng dụng', type: 'text', cols: 6 },
      { key: 'admin_logo_title', label: 'Tiêu đề logo', type: 'text', cols: 6 },
      { key: 'admin_welcome_title', label: 'Tiêu đề chào mừng', type: 'text', cols: 12 },
      { key: 'admin_app_description', label: 'Mô tả ứng dụng', type: 'textarea', cols: 12, rows: 4 },
      {
        key: 'admin_background_image',
        label: 'Ảnh nền trang quản trị',
        type: 'image',
        accept: '.png,.jpg,.jpeg,.webp,.svg',
        hint: 'Cho phép PNG, JPG, JPEG, WEBP, SVG.',
      },
    ],
  },
  {
    key: 'org_select_page',
    title: 'Trang chọn tổ chức',
    icon: 'tabler-building-community',
    subtitle: 'Thiết lập nội dung hiển thị khi người dùng chọn tổ chức làm việc.',
    fields: [
      { key: 'org_select_title', label: 'Tiêu đề', type: 'text', cols: 12 },
      { key: 'org_select_description', label: 'Mô tả', type: 'textarea', cols: 12, rows: 4 },
      {
        key: 'org_select_background_image',
        label: 'Ảnh nền trang chọn tổ chức',
        type: 'image',
        accept: '.png,.jpg,.jpeg,.webp,.svg',
        hint: 'Cho phép PNG, JPG, JPEG, WEBP, SVG.',
      },
    ],
  },
  {
    key: 'social',
    title: 'Mạng xã hội',
    icon: 'tabler-brand-facebook',
    subtitle: 'Các liên kết mạng xã hội và kênh liên hệ công khai.',
    fields: [
      { key: 'social_facebook', label: 'Facebook', type: 'text', cols: 6 },
      { key: 'social_twitter', label: 'Twitter / X', type: 'text', cols: 6 },
      { key: 'social_youtube', label: 'YouTube', type: 'text', cols: 6 },
      { key: 'social_tiktok', label: 'TikTok', type: 'text', cols: 6 },
      { key: 'social_gmail', label: 'Gmail', type: 'text', cols: 6 },
      { key: 'social_email', label: 'Email', type: 'text', cols: 6 },
    ],
  },
  {
    key: 'api',
    title: 'Kết nối API ngoài',
    icon: 'tabler-plug-connected',
    subtitle: 'Thông tin endpoint và token của các tích hợp bên ngoài.',
    fields: [
      { key: 'api_gemini_url', label: 'Gemini URL', type: 'text', cols: 6 },
      { key: 'api_gemini_token', label: 'Gemini Token', type: 'password', cols: 6 },
      { key: 'api_deepseek_url', label: 'DeepSeek URL', type: 'text', cols: 6 },
      { key: 'api_deepseek_token', label: 'DeepSeek Token', type: 'password', cols: 6 },
      { key: 'api_chatgpt_url', label: 'ChatGPT URL', type: 'text', cols: 6 },
      { key: 'api_chatgpt_token', label: 'ChatGPT Token', type: 'password', cols: 6 },
      { key: 'api_firebase_url', label: 'Firebase URL', type: 'text', cols: 6 },
      { key: 'api_firebase_token', label: 'Firebase Token', type: 'password', cols: 6 },
      { key: 'api_google_maps_url', label: 'Google Maps URL', type: 'text', cols: 6 },
      { key: 'api_google_maps_token', label: 'Google Maps Token', type: 'password', cols: 6 },
      { key: 'api_firebase_enabled', label: 'Kích hoạt Firebase', type: 'switch', cols: 12 },
    ],
  },
  {
    key: 'email',
    title: 'Email',
    icon: 'tabler-mail',
    subtitle: 'Thiết lập giao thức và máy chủ gửi email của hệ thống.',
    fields: [
      {
        key: 'email_protocol',
        label: 'Giao thức',
        type: 'select',
        cols: 6,
        items: [
          { title: 'SMTP', value: 'smtp' },
          { title: 'Sendmail', value: 'sendmail' },
        ],
      },
      { key: 'email_sender_name', label: 'Tên người gửi', type: 'text', cols: 6 },
      { key: 'email_sender_address', label: 'Địa chỉ người gửi', type: 'text', cols: 6 },
      { key: 'email_smtp_host', label: 'SMTP Host', type: 'text', cols: 6 },
      { key: 'email_smtp_username', label: 'SMTP Username', type: 'text', cols: 6 },
      { key: 'email_smtp_password', label: 'SMTP Password', type: 'password', cols: 6 },
      { key: 'email_smtp_port', label: 'SMTP Port', type: 'number', cols: 6 },
      {
        key: 'email_smtp_encryption',
        label: 'Mã hóa',
        type: 'select',
        cols: 6,
        items: [
          { title: 'TLS', value: 'tls' },
          { title: 'SSL', value: 'ssl' },
          { title: 'Không dùng', value: 'none' },
        ],
      },
      { key: 'email_test_address', label: 'Email kiểm tra', type: 'text', cols: 6 },
    ],
  },
  {
    key: 'sms',
    title: 'SMS',
    icon: 'tabler-message',
    subtitle: 'Thiết lập kết nối và thông tin kiểm tra SMS.',
    fields: [
      { key: 'sms_server', label: 'SMS Server', type: 'text', cols: 6 },
      { key: 'sms_username', label: 'SMS Username', type: 'text', cols: 6 },
      { key: 'sms_password', label: 'SMS Password', type: 'password', cols: 6 },
      { key: 'sms_test_phone', label: 'Số điện thoại kiểm tra', type: 'text', cols: 6 },
    ],
  },
  {
    key: 'zalo',
    title: 'Zalo',
    icon: 'tabler-brand-telegram',
    subtitle: 'Thiết lập tích hợp gửi thông báo qua Zalo.',
    fields: [
      { key: 'zalo_server', label: 'Zalo Server', type: 'text', cols: 6 },
      { key: 'zalo_username', label: 'Zalo Username', type: 'text', cols: 6 },
      { key: 'zalo_password', label: 'Zalo Password', type: 'password', cols: 6 },
      { key: 'zalo_sender', label: 'Zalo Sender', type: 'text', cols: 6 },
      { key: 'zalo_template_id', label: 'Template ID', type: 'text', cols: 6 },
      { key: 'zalo_extra_params', label: 'Tham số mở rộng', type: 'textarea', cols: 12, rows: 4 },
    ],
  },
  {
    key: 'chat',
    title: 'Chat',
    icon: 'tabler-messages',
    subtitle: 'Thiết lập máy chủ chat, email tiêu đề và thông tin kiểm tra.',
    fields: [
      { key: 'chat_server', label: 'Chat Server', type: 'text', cols: 6 },
      { key: 'chat_api_key', label: 'API Key', type: 'password', cols: 6 },
      { key: 'chat_sender', label: 'Người gửi', type: 'text', cols: 6 },
      { key: 'chat_receiver', label: 'Người nhận', type: 'text', cols: 6 },
      { key: 'chat_room', label: 'Phòng chat', type: 'text', cols: 6 },
      { key: 'chat_message', label: 'Tin nhắn mẫu', type: 'textarea', cols: 6, rows: 4 },
      { key: 'chat_department', label: 'Phòng ban', type: 'text', cols: 6 },
      { key: 'chat_email_title', label: 'Tiêu đề email', type: 'text', cols: 6 },
      { key: 'chat_test_type', label: 'Loại kiểm tra', type: 'text', cols: 6 },
    ],
  },
  {
    key: 'log',
    title: 'Cấu hình nhật ký',
    icon: 'tabler-file-text',
    subtitle: 'Thiết lập thời gian lưu trữ nhật ký hoạt động.',
    fields: [
      { key: 'log_retention_days', label: 'Số ngày lưu trữ', type: 'number', cols: 6 },
    ],
  },
]

export const createEmptySettingState = () => Object.fromEntries(
  coreSettingGroups.map(group => [
    group.key,
    Object.fromEntries(group.fields.map(field => [field.key, field.type === 'switch' ? false : ''])),
  ]),
)
