export default {
  name: 'user',
  displayName: 'Users',
  group: 'auth',
  navOrder: 90,
  path: 'src/modules/auth/user',
  servicePaths: ['src/modules/auth/user/services/userService.js'],
  purpose: 'Quan ly nguoi dung he thong, phan quyen theo to chuc va profile ca nhan.',
  features: [
    'Danh sach user co filter, search, sort va pagination',
    'Tao, sua, xoa user',
    'Bulk delete va bulk status',
    'Import/export Excel',
    'Profile tabs: info, trends, activity logs, notifications',
  ],
  api: [
    { method: 'GET', endpoint: '/users', service: 'fetchUsers', description: 'Danh sach user' },
    { method: 'GET', endpoint: '/users/:id', service: 'fetchUser', description: 'Chi tiet user' },
    { method: 'POST', endpoint: '/users', service: 'createUser', description: 'Tao user' },
    { method: 'PUT', endpoint: '/users/:id', service: 'updateUser', description: 'Cap nhat user' },
    { method: 'DELETE', endpoint: '/users/:id', service: 'deleteUser', description: 'Xoa user' },
    { method: 'PATCH', endpoint: '/users/:id/status', service: 'changeUserStatus', description: 'Doi trang thai user' },
    { method: 'POST', endpoint: '/users/bulk-delete', service: 'bulkDeleteUsers', description: 'Xoa hang loat' },
    { method: 'PATCH', endpoint: '/users/bulk-status', service: 'bulkUpdateUserStatus', description: 'Cap nhat trang thai hang loat' },
    { method: 'GET', endpoint: '/users/stats', service: 'fetchUserStats', description: 'Thong ke user' },
    { method: 'GET', endpoint: '/users/export', service: 'exportUsers', description: 'Xuat Excel' },
    { method: 'GET', endpoint: '/users/template', service: 'downloadUserTemplate', description: 'Tai file mau' },
    { method: 'POST', endpoint: '/users/import', service: 'importUsers', description: 'Nhap Excel' },
  ],
}
