export default {
  name: 'meetings',
  displayName: 'Meetings',
  group: 'business',
  navOrder: 10,
  path: 'src/modules/meetings',
  servicePaths: ['src/modules/meetings/services/meetingService.js'],
  purpose: 'Quan ly nghiep vu hop khong giay, participant flow, tai lieu, bieu quyet va ket luan.',
  features: [
    'CRUD cuoc hop',
    'Quan ly participants, documents, votings, conclusions',
    'Participant flow my-meetings',
    'Global lists va danh muc phu tro',
    'Realtime meeting updates',
  ],
  api: [
    { method: 'GET', endpoint: '/meetings/stats', service: 'fetchMeetingsOverview', description: 'Thong ke meeting dashboard' },
    { method: 'GET', endpoint: '/meetings/export', service: 'exportMeetings', description: 'Xuat danh sach cuoc hop' },
    { method: 'POST', endpoint: '/meetings/import', service: 'importMeetings', description: 'Nhap danh sach cuoc hop' },
    { method: 'GET', endpoint: '/meetings', service: 'fetchMeetings', description: 'Danh sach cuoc hop' },
    { method: 'GET', endpoint: '/meetings/:id', service: 'fetchMeeting', description: 'Chi tiet cuoc hop' },
    { method: 'POST', endpoint: '/meetings', service: 'createMeeting', description: 'Tao cuoc hop' },
    { method: 'PUT', endpoint: '/meetings/:id', service: 'updateMeeting', description: 'Cap nhat cuoc hop' },
    { method: 'DELETE', endpoint: '/meetings/:id', service: 'deleteMeeting', description: 'Xoa cuoc hop' },
    { method: 'PATCH', endpoint: '/meetings/:id/status', service: 'changeMeetingStatus', description: 'Doi trang thai cuoc hop' },
    { method: 'GET', endpoint: '/meeting-types', service: 'fetchMeetingTypes', description: 'Danh muc loai cuoc hop' },
    { method: 'GET', endpoint: '/attendee-groups', service: 'fetchAttendeeGroups', description: 'Danh muc nhom thanh phan tham du' },
    { method: 'GET', endpoint: '/meeting-document-types', service: 'fetchDocumentTypes', description: 'Danh muc loai tai lieu meeting' },
    { method: 'GET', endpoint: '/meeting-document-fields', service: 'fetchDocumentFields', description: 'Danh muc linh vuc tai lieu meeting' },
    { method: 'GET', endpoint: '/participant/my-meetings', service: 'fetchMyMeetings', description: 'Danh sach cuoc hop cua toi' },
    { method: 'GET', endpoint: '/admin/meetings/all-votings', service: 'fetchVotes', description: 'Danh sach bieu quyet toan he thong' },
    { method: 'GET', endpoint: '/admin/meetings/all-documents', service: 'fetchDocuments', description: 'Danh sach tai lieu toan he thong' },
    { method: 'GET', endpoint: '/admin/meetings/all-conclusions', service: 'fetchConclusions', description: 'Danh sach ket luan toan he thong' },
    { method: 'GET', endpoint: '/admin/meetings/all-participants', service: 'fetchAttendees', description: 'Danh sach nguoi tham gia toan he thong' },
  ],
}
