export default {
  name: 'organizations',
  displayName: 'Organizations',
  group: 'auth',
  navOrder: 80,
  path: 'src/modules/auth/organizations',
  servicePaths: ['src/modules/auth/organizations/services/organizationService.js'],
  purpose: 'Quan ly cay to chuc va boi canh lam viec theo to chuc.',
  features: [
    'Danh sach to chuc',
    'Danh sach to chuc cong khai',
    'Dropdown organization cong khai',
    'Tree organization',
    'Tao, sua, xoa to chuc',
    'Bulk delete va bulk status',
    'Import/export Excel',
  ],
  api: [
    { method: 'GET', endpoint: '/organizations', service: 'fetchOrganizations', description: 'Danh sach to chuc' },
    { method: 'GET', endpoint: '/organizations/public', service: 'fetchPublicOrganizations', description: 'Danh sach to chuc cong khai' },
    { method: 'GET', endpoint: '/organizations/public-options', service: 'fetchPublicOrganizationOptions', description: 'Danh sach to chuc cong khai toi gian cho dropdown' },
    { method: 'GET', endpoint: '/organizations/:id', service: 'fetchOrganization', description: 'Chi tiet to chuc' },
    { method: 'POST', endpoint: '/organizations', service: 'createOrganization', description: 'Tao to chuc' },
    { method: 'PUT', endpoint: '/organizations/:id', service: 'updateOrganization', description: 'Cap nhat to chuc' },
    { method: 'DELETE', endpoint: '/organizations/:id', service: 'deleteOrganization', description: 'Xoa to chuc' },
    { method: 'PATCH', endpoint: '/organizations/:id/status', service: 'changeOrganizationStatus', description: 'Doi trang thai' },
    { method: 'GET', endpoint: '/organizations/tree', service: 'fetchOrganizationTree', description: 'Cay to chuc' },
    { method: 'POST', endpoint: '/organizations/bulk-delete', service: 'bulkDeleteOrganizations', description: 'Xoa hang loat' },
    { method: 'PATCH', endpoint: '/organizations/bulk-status', service: 'bulkUpdateOrganizationStatus', description: 'Cap nhat trang thai hang loat' },
    { method: 'GET', endpoint: '/organizations/stats', service: 'fetchOrganizationStats', description: 'Thong ke to chuc' },
    { method: 'GET', endpoint: '/organizations/export', service: 'exportOrganizations', description: 'Xuat Excel' },
    { method: 'POST', endpoint: '/organizations/import', service: 'importOrganizations', description: 'Nhap Excel' },
  ],
}
