import { API_ADMIN_MEETINGS, API_BASE, API_PARTICIPANT } from '../configs'

export const fetchMeetingDocuments = meetingId => $api(`${API_BASE}/${meetingId}/documents`)
export const createMeetingDocument = (meetingId, data) => $api(`${API_BASE}/${meetingId}/documents`, { method: 'POST', body: data })
export const updateMeetingDocument = (meetingId, docId, data) => $api(`${API_BASE}/${meetingId}/documents/${docId}`, { method: 'PUT', body: data })
export const deleteMeetingDocument = (meetingId, docId) => $api(`${API_BASE}/${meetingId}/documents/${docId}`, { method: 'DELETE' })

export const fetchMeetingConclusions = meetingId => $api(`${API_BASE}/${meetingId}/conclusions`)
export const createMeetingConclusion = (meetingId, data) => $api(`${API_BASE}/${meetingId}/conclusions`, { method: 'POST', body: data })
export const updateMeetingConclusion = (meetingId, conclusionId, data) => $api(`${API_BASE}/${meetingId}/conclusions/${conclusionId}`, { method: 'PUT', body: data })
export const deleteMeetingConclusion = (meetingId, conclusionId) => $api(`${API_BASE}/${meetingId}/conclusions/${conclusionId}`, { method: 'DELETE' })

export const fetchMeetingVotes = meetingId => $api(`${API_BASE}/${meetingId}/votings`)
export const createMeetingVote = (meetingId, data) => $api(`${API_BASE}/${meetingId}/votings`, { method: 'POST', body: data })
export const updateMeetingVote = (meetingId, voteId, data) => $api(`${API_BASE}/${meetingId}/votings/${voteId}`, { method: 'PUT', body: data })
export const deleteMeetingVote = (meetingId, voteId) => $api(`${API_BASE}/${meetingId}/votings/${voteId}`, { method: 'DELETE' })
export const openVoting = (meetingId, voteId) => $api(`${API_BASE}/${meetingId}/votings/${voteId}/open`, { method: 'PATCH' })
export const closeVoting = (meetingId, voteId) => $api(`${API_BASE}/${meetingId}/votings/${voteId}/close`, { method: 'PATCH' })
export const castVote = (meetingId, voteId, choice) => $api(`${API_BASE}/${meetingId}/votings/${voteId}/vote`, { method: 'POST', body: { choice } })
export const fetchVotingResults = (meetingId, voteId) => $api(`${API_BASE}/${meetingId}/votings/${voteId}/results`)

export const fetchMeetingParticipants = meetingId => $api(`${API_BASE}/${meetingId}/participants`)
export const createMeetingParticipant = (meetingId, data) => $api(`${API_BASE}/${meetingId}/participants`, { method: 'POST', body: data })
export const updateMeetingParticipant = (meetingId, participantId, data) => $api(`${API_BASE}/${meetingId}/participants/${participantId}`, { method: 'PUT', body: data })
export const deleteMeetingParticipant = (meetingId, participantId) => $api(`${API_BASE}/${meetingId}/participants/${participantId}`, { method: 'DELETE' })
export const checkinMeetingParticipant = (meetingId, participantId, data) => $api(`${API_BASE}/${meetingId}/participants/${participantId}/checkin`, { method: 'PATCH', body: data })
export const selfCheckinMeetingParticipant = meetingId => $api(`${API_PARTICIPANT}/meetings/${meetingId}/self-checkin`, { method: 'POST' })
export const fetchAvailableDelegates = meetingId => $api(`${API_ADMIN_MEETINGS}/${meetingId}/participant-candidates`)

export const fetchPersonalNotes = meetingId => $api(`${API_PARTICIPANT}/meetings/${meetingId}/personal-notes`)
export const createPersonalNote = (meetingId, data) => $api(`${API_PARTICIPANT}/meetings/${meetingId}/personal-notes`, { method: 'POST', body: data })
export const updatePersonalNote = (meetingId, noteId, data) => $api(`${API_PARTICIPANT}/meetings/${meetingId}/personal-notes/${noteId}`, { method: 'PUT', body: data })
export const deletePersonalNote = (meetingId, noteId) => $api(`${API_PARTICIPANT}/meetings/${meetingId}/personal-notes/${noteId}`, { method: 'DELETE' })

export const fetchSpeechRequests = meetingId => $api(`${API_BASE}/${meetingId}/speech-requests`)
export const fetchMySpeechRequests = meetingId => $api(`${API_PARTICIPANT}/meetings/${meetingId}/speech-requests/mine`)
export const createSpeechRequest = (meetingId, data = {}) => $api(`${API_PARTICIPANT}/meetings/${meetingId}/speech-requests`, { method: 'POST', body: data })
export const deleteSpeechRequest = (meetingId, requestId) => $api(`${API_BASE}/${meetingId}/speech-requests/${requestId}`, { method: 'DELETE' })
export const approveSpeechRequest = (meetingId, requestId) => $api(`${API_BASE}/${meetingId}/speech-requests/${requestId}/approve`, { method: 'PATCH' })
export const rejectSpeechRequest = (meetingId, requestId) => $api(`${API_BASE}/${meetingId}/speech-requests/${requestId}/reject`, { method: 'PATCH' })

export const fetchParticipantMeetingDocuments = meetingId => $api(`${API_PARTICIPANT}/meetings/${meetingId}/documents`)
export const fetchParticipantMeetingConclusions = meetingId => $api(`${API_PARTICIPANT}/meetings/${meetingId}/conclusions`)
export const fetchCurrentVoting = meetingId => $api(`${API_PARTICIPANT}/meetings/${meetingId}/votings/current`)
export const castParticipantVote = (meetingId, voteId, choice) => $api(`${API_PARTICIPANT}/meetings/${meetingId}/votings/${voteId}/vote`, { method: 'POST', body: { choice } })
export const fetchParticipantVotingResult = (meetingId, voteId) => $api(`${API_PARTICIPANT}/meetings/${meetingId}/votings/${voteId}/result`)
