export const routes = [
  {
    path: '/business-overview',
    name: 'meetings-business-overview',
    component: () => import('../views/overview/BusinessOverviewPage.vue'),
  },
  {
    path: '/meetings',
    redirect: { name: 'meetings-list' },
  },
  {
    path: '/meetings/my-calendar',
    name: 'meetings-my-calendar',
    component: () => import('../views/management/MyCalendarPage.vue'),
    meta: { action: 'index', subject: 'MyMeeting' },
  },
  {
    path: '/meetings/list',
    name: 'meetings-list',
    component: () => import('../views/management/MeetingListPage.vue'),
    meta: { action: 'index', subject: 'Meeting' },
  },
  {
    path: '/meetings/votes',
    name: 'meetings-votes-list',
    component: () => import('../views/management/VotesListPage.vue'),
    meta: { action: 'index', subject: 'MeetingVoting' },
  },
  {
    path: '/meetings/documents',
    name: 'meetings-documents-list',
    component: () => import('../views/management/DocumentsListPage.vue'),
    meta: { action: 'index', subject: 'MeetingDocument' },
  },
  {
    path: '/meetings/conclusions',
    name: 'meetings-conclusions-list',
    component: () => import('../views/management/ConclusionsListPage.vue'),
    meta: { action: 'index', subject: 'MeetingConclusion' },
  },
  {
    path: '/meetings/attendee-groups',
    name: 'meetings-attendee-groups',
    component: () => import('../views/catalogs/participants/AttendeeGroupListPage.vue'),
    meta: { action: 'index', subject: 'AttendeeGroup' },
  },
  {
    path: '/meetings/document-types',
    name: 'meetings-document-types',
    component: () => import('../views/catalogs/documents/DocumentTypeListPage.vue'),
    meta: { action: 'index', subject: 'MeetingDocumentType' },
  },
  {
    path: '/meetings/document-fields',
    name: 'meetings-document-fields',
    component: () => import('../views/catalogs/documents/DocumentFieldListPage.vue'),
    meta: { action: 'index', subject: 'MeetingDocumentField' },
  },
  {
    path: '/meetings/meeting-types',
    name: 'meetings-meeting-types',
    component: () => import('../views/catalogs/meetings/MeetingTypeListPage.vue'),
    meta: { action: 'index', subject: 'MeetingType' },
  },
  {
    path: '/meetings/live/:id',
    name: 'meetings-live-controller',
    component: () => import('../views/admin/live/LiveMeetingController.vue'),
    meta: { action: 'live-control', subject: 'Meeting' },
  },
  {
    path: '/meetings/create',
    name: 'meetings-create',
    component: () => import('../views/admin/edit/MeetingEditPage.vue'),
    meta: { action: 'store', subject: 'Meeting' },
  },
  {
    path: '/meetings/edit/:id',
    name: 'meetings-edit',
    component: () => import('../views/admin/edit/MeetingEditPage.vue'),
    meta: { action: 'update', subject: 'Meeting' },
  },
  {
    path: '/my-meetings',
    name: 'meetings-participant-my-meetings',
    component: () => import('../views/participant/MyMeetingsPage.vue'),
    meta: { action: 'index', subject: 'MyMeeting' },
  },
  {
    path: '/my-meetings/:id',
    name: 'meetings-participant-details',
    component: () => import('../views/participant/details/MeetingDetailsPage.vue'),
    meta: { action: 'show', subject: 'MyMeeting' },
  },
]
