export const routes = [
  {
    path: '/business-overview',
    name: 'meetings-business-overview',
    component: () => import('../views/BusinessOverviewPage.vue'),
    meta: { action: 'read', subject: 'Meeting' },
  },
  {
    path: '/activity-logs',
    name: 'system-activity-logs',
    component: () => import('../views/ActivityLogsPage.vue'),
  },
  {
    path: '/meetings',
    name: 'meetings-list',
    component: () => import('../views/MeetingListPage.vue'),
    meta: { action: 'read', subject: 'Meeting' },
  },
  {
    path: '/meetings/votes',
    name: 'meetings-votes-list',
    component: () => import('../views/VotesListPage.vue'),
    meta: { action: 'read', subject: 'Meeting' },
  },
  {
    path: '/meetings/documents',
    name: 'meetings-documents-list',
    component: () => import('../views/DocumentsListPage.vue'),
    meta: { action: 'read', subject: 'Meeting' },
  },
  {
    path: '/meetings/conclusions',
    name: 'meetings-conclusions-list',
    component: () => import('../views/ConclusionsListPage.vue'),
    meta: { action: 'read', subject: 'Meeting' },
  },
  {
    path: '/meetings/attendees',
    name: 'meetings-attendees-list',
    component: () => import('../views/AttendeesListPage.vue'),
    meta: { action: 'read', subject: 'Meeting' },
  },
  {
    path: '/meetings/attendee-groups',
    name: 'meetings-attendee-groups',
    component: () => import('../views/AttendeeGroupListPage.vue'),
    meta: { action: 'read', subject: 'Meeting' },
  },
  {
    path: '/meetings/document-types',
    name: 'meetings-document-types',
    component: () => import('../views/DocumentTypeListPage.vue'),
    meta: { action: 'read', subject: 'Meeting' },
  },
  {
    path: '/meetings/meeting-types',
    name: 'meetings-meeting-types',
    component: () => import('../views/MeetingTypeListPage.vue'),
    meta: { action: 'read', subject: 'Meeting' },
  },
  {
    path: '/meetings/live/:id',
    name: 'meetings-live-controller',
    component: () => import('../views/admin/live/LiveMeetingController.vue'),
    meta: { action: 'read', subject: 'Meeting' },
  },
  {
    path: '/meetings/edit/:id?',
    name: 'meetings-edit',
    component: () => import('../views/admin/edit/MeetingEditPage.vue'),
    meta: { action: 'update', subject: 'Meeting' },
  },
  {
    path: '/my-meetings',
    name: 'meetings-participant-my-meetings',
    component: () => import('../views/participant/MyMeetingsPage.vue'),
    meta: { action: 'read', subject: 'Meeting' },
  },
  {
    path: '/my-meetings/:id',
    name: 'meetings-participant-details',
    component: () => import('../views/participant/details/MeetingDetailsPage.vue'),
    meta: { action: 'read', subject: 'Meeting' },
  },
]
